### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by bbence84** [ondbyte/super_strapi#2]
Hi! I came accross this nice plugin.
However I cannot seem to run it for generating the class files for the Strapi project...

  Command: **flutter create --no-pub --org xyz.yadunandan --project-name super_strapi_generated -t package ./super_strapi_generated**
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      _makeProject (file:///C:/Users/bence/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/super_strapi-0.9.0-alpha+3/bin/super_strapi.dart:194:17)
#4      _validatePubspec (file:///C:/Users/bence/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/super_strapi-0.9.0-alpha+3/bin/super_strapi.dart:160:27)
<asynchronous suspension>
#5      setupOutPutDirectory (file:///C:/Users/bence/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/super_strapi-0.9.0-alpha+3/bin/super_strapi.dart:140:7)
<asynchronous suspension>
#6      main (file:///C:/Users/bence/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/super_strapi-0.9.0-alpha+3/bin/super_strapi.dart:55:26)
<asynchronous suspension>
pub finished with exit code 255

Seems that the above command is hardcoded, no matter how the project folder is named or configured already.

Thanks!

**Comment by ondbyte** [comment]
I advice not to use this as of now.

**Comment by bbence84** [comment]
Thanks, that's what I thought. :) Any plans to make it working to some extent? Of course, I know it's a free project, just wondering if I can expect it to be working in a few weeks. Thanks!

**Comment by ondbyte** [comment]
Only the generation part is messed up, but generated code works like a charm, never used it since a year, if you really gonna take advantage of this plug-in, I would fix it.
